 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  sgg_concate_rel_detection: # name of the dataset builder
    dataset_card: dataset_card/coco_caption.md
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: 
            - all_sgg_data/train.json
          storage: 
            - all_sgg_data/train.json

        val:
          url: 
            - all_sgg_data/val.json
          storage: 
            - all_sgg_data/val.json

      images:
        storage: '.'
