 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  vg_rel_detection: # name of the dataset builder
    dataset_card: dataset_card/coco_caption.md
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: 
            - vg/vg_motif_anno/VG-SGG-train.h5
            - vg/vg_motif_anno/image_data.json
          storage: 
            - vg/vg_motif_anno/VG-SGG-train.h5
            - vg/vg_motif_anno/image_data.json
        train_zs_pred:
          url: 
            - vg/vg_motif_anno/VG-SGG-train_zs_pred.h5
            - vg/vg_motif_anno/image_data.json
          storage: 
            - vg/vg_motif_anno/VG-SGG-train_zs_pred.h5
            - vg/vg_motif_anno/image_data.json
        val:
          url: 
            - vg/vg_motif_anno/VG-SGG-val.h5
            - vg/vg_motif_anno/image_data.json
          storage: 
            - vg/vg_motif_anno/VG-SGG-val.h5
            - vg/vg_motif_anno/image_data.json

        test:
          url: 
            - vg/vg_motif_anno/VG-SGG-test.h5
            - vg/vg_motif_anno/image_data.json
          storage: 
            - vg/vg_motif_anno/VG-SGG-test.h5
            - vg/vg_motif_anno/image_data.json
      images:
        storage: vg/VG_100k_images